### PR TITLE
Initial changes to the Role

### PR DESCRIPTION
**Pull request by makentenza**
Initial changes to adapt the role to the new location, adding CI and update/remove everything that needs to be updated/removed

### CODE REVIEW

**Comment by makentenza** [comment]
@rhmk @tbludau this is still WIP but could you quick review it. I'm still missing the 3rd option discussed with @rhmk for the installation. So far covering 'RPM' and 'SAR'.

The main idea for this PR is to:
- Simplify the actual role
- Make it idempotent
- Add a CI mechanism (Travis) to the repo

**Comment by makentenza** [comment]
@rickgcv just pushed the code for the 3rd scenario. PTAL and we can discuss here

**Comment by makentenza** [comment]
@rickgcv just pushed the code for the 3rd scenario. PTAL and we can discuss here

**Comment by makentenza** [comment]
@rickgcv just remove the WIP tag from the name, this is ready to review

**Review by rickgcv — APPROVED** [review]
LGTM

**Pull request merged**
